### ISSUE TITLE
wget

### ISSUE THREAD

**Issue by iraizo** [maxwell187/leaked-stuff#1]
congratulation du kannst wget benutzen zu dumm fürs leben xd ist wohl doch nur am pc und baut scheiße

**Comment by iraizo** [comment]
sogar zu dumm cloudbric zu removen xd alter wie ein autist

**Comment by iraizo** [comment]
mein kleiner fanboy :^)

**Comment by maxwell187** [comment]
kollege, als ob ich auch nur irgendeine arbeit da rein gesteckt hätte

meine kollegen und ich haben deinen autismus gesehen (luby hat erzählt haha) und dachten uns jamoin erstmal kurz spaß haben

btw, ich hab deine coc accs

**Comment by iraizo** [comment]
wen juckt das? lol

**Comment by iraizo** [comment]
du kannst keine arbeit rein stecken weil du kein irl leben hast lol

**Comment by maxwell187** [comment]
Das macht 0 sinn

Ich mache jetzt seit nem monat ungf. fast garnix mehr am pc und wenn, dann zum leute triggern oder coden

**Comment by maxwell187** [comment]
Such dir mal ne freundin und n leben und hör auf csgo zu spielen ahha

**Comment by iraizo** [comment]
:^) hab eine, ich spiele was ich will du idiot
